/**
 * File: audio.h
 * Description: Cart-shared audio buffer producer + app-facing API.
 *
 * The RP refills a 1024-byte cart buffer at CART_AUDIO_BUFFER_OFFSET
 * once per VBL via audio_render_frame() (paced to ~50 Hz via
 * time_us_32). Which back-end consumes it is decided at RUNTIME by
 * the m68k, which detects STE DMA sound at boot (_SND cookie) and
 * reports the result to the RP over the cart bus every VBL:
 *
 *   AUDIO_MODE_DMA  -- STE-compatible DMA sound (STE, Mega STE, TT).
 *                      25,033 Hz 8-bit SIGNED mono, played by the DMA
 *                      sound chip at no CPU cost. 500 B/VBL.
 *   AUDIO_MODE_YM   -- plain ST. 5,585 Hz (vA, vB) YM2149 volume
 *                      pairs played by the Timer-B IRQ through the
 *                      Ghostbusters LUT. 224 B/VBL.
 *
 * Apps install audio content one of three ways. The first two take
 * plain UNSIGNED 8-bit mono PCM at any rate and the library cooks it
 * into whichever format the live back-end wants, so the same asset
 * plays on every machine:
 *
 *   1. audio_play_loop(pcm, bytes, rate_hz) -- loop a baked-in
 *      buffer (e.g. audio_sample_data[] from tools/wav_to_ym4.py
 *      --mode raw-byte).
 *
 *   2. audio_play_yms_file(path) -- stream a .YMS file from SD.
 *
 *   3. audio_set_fill_callback(cb) -- low-level. `cb(buf, bytes)` is
 *      invoked once per refill and must write exactly `bytes` bytes
 *      in the format audio_get_mode() reports. Use for sources that
 *      cook their own audio (e.g. a live decoder).
 *
 * If no callback is installed, audio_render_frame() is a no-op and
 * the cart buffer stays whatever audio_init() left it (zero =
 * silence in both formats). Calling audio_set_fill_callback(NULL)
 * re-enters this silent state.
 */

#ifndef AUDIO_H_INCLUDED
#define AUDIO_H_INCLUDED

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Audio back-end, chosen at runtime from the m68k's _SND detection
 * (reported over the cart bus; audio_consume_rom3_sample decodes the
 * report out of the ROM3 ring). Governs the per-VBL refill size and
 * the format the fill callback must produce. Defaults to SILENT until
 * the first report arrives. */
typedef enum {
  AUDIO_MODE_SILENT = 0, /* zeros -- pre-report / no audio      */
  AUDIO_MODE_YM,         /* 224 B/VBL: 112 (vA, vB) pairs       */
  AUDIO_MODE_DMA         /* ~500 B/VBL of signed PCM, steered   */
} audio_mode_t;

/* Per-VBL fill callback. The library invokes this from
 * audio_render_frame() with `buf` pointing into the cart audio
 * buffer and `bytes` set to the live back-end's per-VBL consumption:
 * a fixed 224 for YM, and for DMA whatever the m68k measured the chip
 * to be eating this frame (near 500, steered every few frames -- see
 * audio_set_fill_bytes). The callback must write exactly that many
 * bytes in the matching format; the library does not zero on entry.
 *
 * Called from the main loop at ~50 Hz; must not block. */
typedef void (*audio_fill_cb_t)(uint8_t *buf, uint32_t bytes);

/* Set the back-end (idempotent). Called by the cart-bus capability
 * decoder; changes the refill size asked of the callback. */
void audio_set_mode(audio_mode_t mode);

/* Current back-end, for a low-level fill callback to pick its
 * output format. */
audio_mode_t audio_get_mode(void);

/* Bytes per VBL currently asked of the fill callback. */
uint32_t audio_get_fill_bytes(void);

/* Set the per-VBL refill size. Only meaningful for STE DMA sound,
 * where the m68k measures what the chip actually consumes per frame
 * and sends it back -- that figure is near 501, not 500, and differs
 * between machines because the sound DMA and the video are clocked
 * separately. Ignored in YM mode, whose rate is fixed by the Timer-B
 * divider, and for values outside the cart buffer. */
void audio_set_fill_bytes(uint32_t bytes);

/* commemul ring consumer. Passed each captured ROM3 sample by the
 * dispatcher in fb.c; filters for the m68k's sound-capability and
 * buffer-length report windows and applies what it finds. */
void audio_consume_rom3_sample(uint16_t addr_lsb);

/* Initialise the cart audio buffer pointer; clear any previously
 * installed callback. Call once during boot. */
void audio_init(void);

/* Drain the per-VBL pacing timer and (if a callback is installed)
 * invoke it to refill the cart buffer. Call once per main-loop
 * iteration; the internal time_us_32 pacing throttles to ~50 Hz. */
void audio_render_frame(void);

/* Install (or clear, if cb == NULL) the fill callback. */
void audio_set_fill_callback(audio_fill_cb_t cb);

/* Convenience: loop a static UNSIGNED 8-bit mono PCM buffer
 * (silence = 0x80) indefinitely, resampled and cooked to the live
 * back-end's format on every refill. `pcm` must remain live for as
 * long as playback continues (typically a `static const uint8_t[]`
 * baked into the firmware -- e.g. audio_sample_data[] generated by
 * `tools/wav_to_ym4.py --mode raw-byte`). `bytes` is the length of
 * one loop iteration; playback wraps at byte `bytes-1` back to byte
 * 0. `rate_hz` is the sample rate of `pcm` (e.g.
 * AUDIO_SAMPLE_RATE_HZ from the generated header).
 *
 * Replaces any previously installed callback. */
void audio_play_loop(const uint8_t *pcm, uint32_t bytes, uint32_t rate_hz);

/* Convenience: open a .YMS file from SD and stream it on loop.
 * The file format (produced by `tools/wav_to_ym4.py --mode raw-byte
 * --yms-output`) is a 16-byte header followed by the raw byte body:
 *   off  0:  'Y' 'M' 'S' '1'        magic
 *   off  4:  uint32 rate_hz         little-endian; the body's PCM
 *                                   rate, any value up to 25,600 Hz
 *   off  8:  uint32 data_len_bytes  little-endian
 *   off 12:  uint8  mode_tag        3 = raw-byte (unsigned 8-bit
 *                                       mono PCM; the only mode the
 *                                       universal path can cook)
 *   off 13:  uint8[3]              reserved (= 0)
 *   off 16:  raw byte body         unsigned 8-bit mono PCM
 *
 * The library opens the file, validates the header, and installs a
 * callback that reads from the file on every per-VBL refill. SD is
 * assumed mounted; call after sdcard_initFilesystem(). The file
 * loops at EOF (cursor wraps back to the data start).
 *
 * Returns 0 on success, negative on failure (open failed / short
 * read / bad magic / rate out of range / unsupported mode). On
 * failure the previously installed callback is preserved -- apps can
 * use this to fall back to a baked-in audio_play_loop(). */
int audio_play_yms_file(const char *path);

#ifdef __cplusplus
}
#endif

#endif /* AUDIO_H_INCLUDED */
